language: node_js

node_js:
  - lts/*

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  target_branch: master
  local_dir: dist
  github_token: $GITHUB_TOKEN
  on:
    branch: develop
