name: Single Check
on:
  - push
  
jobs:
  build-site:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
      - name: Build Page
        uses: build-page@v1
      
    
