name: Release to Production
on:
  release:
    types: [created, released, edited]
  
jobs:
  build-site:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm run build